@BASEURL = http://localhost:3001/api
@HOST = localhost:3001

###
# @name SignUp
POST {{BASEURL}}/user/sign-up
Host: {{HOST}}
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "example_password"
}

###
# @name SignIn
POST {{BASEURL}}/user/sign-in
Host: {{HOST}}
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "example_password"
}

###
# @name GetAllTasks
GET {{BASEURL}}/tasks?page=1
Host: {{HOST}}
Authorization: Bearer token
Content-Type: application/json

###
# @name GetTask
GET {{BASEURL}}/task/:id
Host: {{HOST}}
Authorization: Bearer token
Content-Type: application/json

###
# @name CreateTask
POST {{BASEURL}}/task
Host: {{HOST}}
Authorization: Bearer token
Content-Type: application/json

{
  "title": "example task",
  "description": "example task description"
}

###
# @name UpdateTask
PATCH  {{BASEURL}}/task/:id
Host: {{HOST}}
Authorization: Bearer token
Content-Type: application/json

{
  "title": "Vamos a escola Zezinho"
}

###
# @name DeleteTask
DELETE {{BASEURL}}/task/:id
Host: {{HOST}}
Authorization: Bearer token
Content-Type: application/json
